package com.medibook.payment.entity;

import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDateTime;

/*
 * This is the Payment entity.
 * It maps directly to the payments table in MySQL.
 *
 * Think of it like a digital receipt stored in our database.
 * Every payment attempt creates one record here.
 * Whether it succeeded, failed, or was refunded —
 * every transaction is stored permanently.
 *
 * Why store failed payments too?
 * → Audit trail — PDF requires this
 * → Admin can see payment failure patterns
 * → Patient can see their payment history
 * → Debugging payment issues is easier
 *
 * How it connects to other entities:
 * → appointmentId links to Appointment (UC4)
 * → patientId links to User (UC1)
 * → one appointment can have only one payment record
 *
 * RAZORPAY READY:
 * → razorpayOrderId stores real Razorpay order ID
 * → razorpayPaymentId stores real Razorpay payment ID
 * → razorpaySignature stores verification signature
 * → these fields are null in mock mode
 * → filled with real values when Razorpay integrated
 * → zero schema changes needed when we swap to real gateway
 */
@Entity
@Table(name = "payments")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Payment {

    /*
     * Unique ID for every payment record.
     * Auto generated by MySQL.
     * Referenced by refund requests and admin queries.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int paymentId;

    /*
     * Which appointment is this payment for?
     * Links to appointmentId in appointments table (UC4).
     * Unique constraint — one appointment, one payment record.
     * Cannot pay twice for same appointment.
     */
    @Column(nullable = false, unique = true)
    private int appointmentId;

    /*
     * Who made this payment?
     * Links to userId in users table (UC1).
     * Used to show payment history on patient dashboard.
     * Also used for security — verify right patient paying.
     */
    @Column(nullable = false)
    private int patientId;

    /*
     * How much was paid?
     * Stored in rupees for readability.
     * When Razorpay integrated → converted to paise internally
     * but stored here in rupees for display.
     */
    @Column(nullable = false)
    private double amount;

    /*
     * What currency was used?
     * Example: INR
     * Stored for international expansion readiness.
     */
    @Column(nullable = false)
    private String currency;

    /*
     * What payment method did patient use?
     * Values: CARD / UPI / NETBANKING / WALLET
     * Shown on payment receipt and history.
     */
    @Column(nullable = false)
    private String paymentMethod;

    /*
     * Current status of this payment.
     * PDF defines exactly 4 values:
     *
     * PENDING  → payment initiated, waiting for confirmation
     *            Razorpay order created, popup not completed yet
     *
     * SUCCESS  → payment confirmed and verified
     *            Appointment is now fully confirmed
     *
     * FAILED   → payment attempt failed
     *            Patient must retry
     *            Appointment stays SCHEDULED waiting for payment
     *
     * REFUNDED → money returned after appointment cancelled
     *            Triggered when patient cancels appointment
     *
     * Default is PENDING when payment first initiated.
     */
    @Column(nullable = false)
    private String status = "PENDING";

    /*
     * Razorpay Order ID.
     * MOCK MODE → "MOCK_ORDER_" + appointmentId
     * RAZORPAY MODE → "order_NBjjkv09NoyHAT" (real from Razorpay)
     *
     * This is created FIRST when payment is initiated.
     * Frontend uses this to open Razorpay payment popup.
     * Stored here so we can match it during verification.
     */
    private String razorpayOrderId;

    /*
     * Razorpay Payment ID.
     * MOCK MODE → "MOCK_PAY_" + timestamp
     * RAZORPAY MODE → "pay_29QQoUBi66xm2f" (real from Razorpay)
     *
     * This comes AFTER patient completes payment.
     * Used to verify payment and initiate refunds.
     * Null until payment is completed by patient.
     */
    private String razorpayPaymentId;

    /*
     * Razorpay Signature for verification.
     * MOCK MODE → null (not needed)
     * RAZORPAY MODE → HMAC-SHA256 hash string
     *
     * When Razorpay sends payment success to frontend:
     * → frontend gets orderId + paymentId + signature
     * → we verify: HMAC(orderId|paymentId, secret) == signature
     * → if matches → payment is genuine → status = SUCCESS
     * → if not matches → payment tampered → status = FAILED
     *
     * This is the core security check of Razorpay integration.
     * Stored here for audit trail purposes.
     */
    private String razorpaySignature;

    /*
     * When was this payment record created?
     * Auto set when payment is first initiated.
     * Shown on patient receipt.
     * Part of PDF audit trail requirement.
     */
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /*
     * When was this payment last updated?
     * Updated when status changes.
     * Example: PENDING → SUCCESS → updated
     *          SUCCESS → REFUNDED → updated again
     * Part of PDF audit trail requirement.
     */
    private LocalDateTime updatedAt;

    /*
     * Any notes about this payment.
     * Example: "Refund initiated due to appointment cancellation"
     * Example: "Payment failed — card declined"
     * Optional — set internally by system not by patient.
     */
    private String notes;

    /*
     * Auto set createdAt and updatedAt when first saved.
     * @PrePersist runs automatically before INSERT.
     * We never set these manually.
     */
    @PrePersist
    public void prePersist() {
        this.createdAt = LocalDateTime.now();
        this.updatedAt = LocalDateTime.now();
    }

    /*
     * Auto update updatedAt every time record changes.
     * @PreUpdate runs automatically before every UPDATE.
     * Every status change is tracked with timestamp.
     * This satisfies PDF audit trail requirement.
     */
    @PreUpdate
    public void preUpdate() {
        this.updatedAt = LocalDateTime.now();
    }
}