package com.medibook.appointment.entity;

import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;

/*
 * This is the Appointment entity.
 * It maps directly to the appointments table in MySQL.
 *
 * Think of it like the actual booking record.
 * When patient picks a doctor, picks a slot, and confirms —
 * one Appointment record is created in this table.
 *
 * This is the most important entity in the entire system.
 * It connects everything together:
 * → Patient (from UC1)
 * → Doctor (from UC2)
 * → Time Slot (from UC3)
 * → Payment (UC5 will link here)
 * → Review (UC6 will link here)
 * → Medical Record (UC8 will link here)
 *
 * Status lifecycle from PDF:
 * SCHEDULED → appointment created, waiting to happen
 * COMPLETED → doctor marked it done
 * CANCELLED → patient or doctor cancelled it
 * NO_SHOW   → nobody marked it complete, auto flagged
 */
@Entity
@Table(name = "appointments")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Appointment {

    /*
     * Unique ID for every appointment.
     * Auto generated by MySQL.
     * Payment, Review, MedicalRecord will reference this.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int appointmentId;

    /*
     * Which patient booked this appointment?
     * Links to userId in users table (UC1).
     * Patient must have role=Patient.
     */
    @Column(nullable = false)
    private int patientId;

    /*
     * Which doctor is this appointment with?
     * Links to providerId in providers table (UC2).
     * Doctor must be verified and available.
     */
    @Column(nullable = false)
    private int providerId;
    
    
    private String patientEmail;

    /*
     * Which time slot was booked?
     * Links to slotId in availability_slots table (UC3).
     * When appointment created → that slot marked as booked.
     * When appointment cancelled → that slot released back.
     */
    @Column(nullable = false)
    private int slotId;

    /*
     * What type of service is this appointment for?
     * Example: General Consultation, Follow-Up, Dental Checkup
     * Doctor sees this before appointment to prepare.
     */
    @Column(nullable = false)
    private String serviceType;

    /*
     * Which date is this appointment on?
     * Example: 2026-04-10
     */
    @Column(nullable = false)
    private LocalDate appointmentDate;

    /*
     * What time does this appointment start?
     * Example: 10:00
     */
    @Column(nullable = false)
    private LocalTime startTime;

    /*
     * What time does this appointment end?
     * Example: 10:30
     */
    @Column(nullable = false)
    private LocalTime endTime;

    /*
     * Current status of this appointment.
     * PDF defines exactly 4 possible values:
     *
     * SCHEDULED   → appointment booked, not yet happened
     * COMPLETED   → doctor marked consultation as done
     * CANCELLED   → patient or doctor cancelled it
     * NO_SHOW     → appointment time passed, nobody marked complete
     *               auto flagged by NoShowDetectionScheduler
     *
     * Default is SCHEDULED when appointment first created.
     */
    @Column(nullable = false)
    private String status = "SCHEDULED";

    /*
     * Any notes from patient about their problem.
     * Example: "Chest pain for 3 days, mild fever"
     * Optional — patient can leave this blank.
     */
    private String notes;

    /*
     * How is the consultation happening?
     * IN_PERSON       → patient visits clinic physically
     * TELECONSULTATION → video call from home
     * PDF defines exactly these two modes.
     */
    @Column(nullable = false)
    private String modeOfConsultation;

    /*
     * When was this appointment record created?
     * Auto set when appointment is first saved.
     * Used in audit trail and analytics.
     */
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /*
     * When was this appointment last updated?
     * Updated whenever status changes.
     * Example: when cancelled, when completed.
     * Used in audit trail — PDF requires this.
     */
    private LocalDateTime updatedAt;

    /*
     * Auto set createdAt and updatedAt before first save.
     * @PrePersist runs automatically before INSERT.
     */
    @PrePersist
    public void prePersist() {
        this.createdAt = LocalDateTime.now();
        this.updatedAt = LocalDateTime.now();
    }

    /*
     * Auto update updatedAt every time record is updated.
     * @PreUpdate runs automatically before every UPDATE.
     * This ensures we always know when status last changed.
     * PDF requires audit trail for all status changes.
     */
    @PreUpdate
    public void preUpdate() {
        this.updatedAt = LocalDateTime.now();
    }
}