package com.medibook.schedule.entity;

import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;

/*
 * This is the AvailabilitySlot entity.
 * It maps directly to the availability_slots table in MySQL.
 *
 * Think of it like one box in a doctor's diary.
 * Each box represents one time window where doctor is free.
 * Example: Dr. Sharma — April 5 — 10:00 to 10:30
 *
 * One slot = one appointment.
 * When patient books that slot → isBooked = true
 * When patient cancels → isBooked = false (slot released)
 * When doctor blocks for leave → isBlocked = true
 *
 * Important business rules from PDF:
 * → Blocked slots are invisible to patients
 * → Expired slots (past date, no booking) are auto deleted
 * → Slot status: Available → Booked → Released
 * → Double booking prevented by optimistic locking (@Version)
 */
@Entity
@Table(name = "availability_slots")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class AvailabilitySlot {

    /*
     * Unique ID for every slot.
     * Auto generated by MySQL.
     * We never set this manually.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int slotId;

    /*
     * Which doctor owns this slot?
     * Links to Provider entity from UC2.
     * Every slot belongs to exactly one doctor.
     */
    @Column(nullable = false)
    private int providerId;

    /*
     * Which date is this slot on?
     * Example: 2026-04-05
     * Patient sees slots grouped by date.
     */
    @Column(nullable = false)
    private LocalDate date;

    /*
     * When does this slot start?
     * Example: 10:00
     * Stored as time only — date is separate field above.
     */
    @Column(nullable = false)
    private LocalTime startTime;

    /*
     * When does this slot end?
     * Example: 10:30
     * endTime - startTime = duration of appointment.
     */
    @Column(nullable = false)
    private LocalTime endTime;

    /*
     * How long is this appointment in minutes?
     * Example: 30
     * Helps calculate how many slots fit in a day.
     */
    @Column(nullable = false)
    private int durationMinutes;

    /*
     * Is this slot already booked by a patient?
     * false = available for booking
     * true  = patient has booked this slot
     *
     * When appointment is created → set to true
     * When appointment is cancelled → set back to false
     * Patients only see slots where isBooked = false
     */
    @Column(nullable = false)
    private boolean isBooked = false;

    /*
     * Has the doctor blocked this slot?
     * false = slot is available
     * true  = doctor blocked it (personal leave, holiday etc)
     *
     * Blocked slots are INVISIBLE to patients.
     * Only doctor and admin can see blocked slots.
     * This is a strict PDF requirement.
     */
    @Column(nullable = false)
    private boolean isBlocked = false;

    /*
     * Is this slot part of a recurring pattern?
     * Values: NONE / DAILY / WEEKLY
     * NONE   = one time slot
     * DAILY  = generated as part of daily recurring slots
     * WEEKLY = generated as part of weekly recurring slots
     *
     * Stored for reference — helps doctor identify
     * which slots were auto generated.
     */
    private String recurrence = "NONE";

    /*
     * When was this slot created?
     * Auto set when slot is first saved.
     * Used in admin analytics and audit trail.
     */
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /*
     * Optimistic locking version field.
     * This is the PDF requirement to prevent double booking.
     *
     * How it works:
     * Patient A and Patient B both try to book same slot
     * at exactly the same time.
     * First one to save → version increments
     * Second one → sees version mismatch → throws exception
     * → Only ONE patient gets the slot
     * → No double booking ever happens
     *
     * This is explicitly called out in PDF non-functional
     * requirements under Data Integrity section.
     */
    @Version
    private int version;

    /*
     * Auto set createdAt when slot is first saved.
     * @PrePersist runs automatically before INSERT.
     * We never set createdAt manually.
     */
    @PrePersist
    public void prePersist() {
        this.createdAt = LocalDateTime.now();
    }
}