package com.medibook.record.entity;

import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDate;
import java.time.LocalDateTime;

/*
 * This is the MedicalRecord entity.
 * It maps directly to the medical_records table in MySQL.
 *
 * Think of it like the patient's file at a hospital.
 * Every time a patient visits a doctor and consultation
 * is marked complete, doctor creates one record here.
 * It contains diagnosis, prescription, notes, and follow up.
 *
 * Important access rules from PDF:
 * → Patient can view ONLY their own records
 * → Doctor can view ONLY records they created
 * → Admin has read only access to ALL records (audit)
 *
 * Important business rules from PDF:
 * → One record per appointment (unique constraint)
 * → Record created only after appointment COMPLETED
 * → Follow up date triggers automatic reminder via UC7
 * → Records encrypted at rest AES-256 (production)
 * → Audit logs maintained for all record access (HIPAA)
 */
@Entity
@Table(name = "medical_records")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class MedicalRecord {

    /*
     * Unique ID for every medical record.
     * Auto generated by MySQL.
     * Payment Review and Notification may reference this.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int recordId;

    /*
     * Which appointment is this record for?
     * Links to appointmentId in appointments table (UC4).
     * UNIQUE constraint enforces one record per appointment.
     * Doctor cannot create two records for same appointment.
     */
    @Column(nullable = false, unique = true)
    private int appointmentId;

    /*
     * Which patient does this record belong to?
     * Links to userId in users table (UC1).
     * Patient uses this to view their own records.
     * Patient can ONLY see records where patientId matches
     * their own userId — PDF access control requirement.
     */
    @Column(nullable = false)
    private int patientId;

    /*
     * Which doctor created this record?
     * Links to providerId in providers table (UC2).
     * Doctor uses this to view records they created.
     * Doctor can ONLY see records where providerId matches
     * their own providerId — PDF access control requirement.
     */
    @Column(nullable = false)
    private int providerId;

    /*
     * What is the diagnosis from consultation?
     * Example: Viral chest infection, Type 2 Diabetes
     * This is the primary medical finding.
     * Cannot be null — core part of every medical record.
     */
    @Column(nullable = false)
    private String diagnosis;

    /*
     * What medicines did doctor prescribe?
     * Example: Amoxicillin 500mg twice daily for 5 days
     * Optional — some consultations have no medicines.
     * Stored as text — doctor writes full prescription.
     */
    private String prescription;

    /*
     * Additional clinical notes from doctor.
     * Example: Patient should rest, avoid cold food.
     * Optional — doctor adds extra observations here.
     */
    @Column(columnDefinition = "TEXT")
    private String notes;

    /*
     * URL of any attached document from S3.
     * Example: https://s3.amazonaws.com/medibook/lab-report.pdf
     * Optional — not every consultation has attachments.
     * In production: AWS S3 URL stored here.
     * In development: local file path or mock URL.
     */
    private String attachmentUrl;

    /*
     * When should patient come back for follow up?
     * Example: 2026-04-25
     * Optional — not every consultation needs follow up.
     *
     * When this is set:
     * → NotificationService sends automatic reminder
     *   to patient on this exact date
     * → This is explicit PDF requirement
     * → RecordServiceImpl checks for follow up records
     *   and triggers notification via scheduler
     */
    private LocalDate followUpDate;

    /*
     * When was this medical record created?
     * Auto set when record is first saved.
     * Used in audit trail — PDF HIPAA requirement.
     * Never updated after first save.
     */
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /*
     * When was this record last updated?
     * Updated when doctor edits record within allowed window.
     * PDF allows doctor to edit record within time window
     * after appointment. After window closes cannot edit.
     * Used in audit trail — PDF HIPAA requirement.
     */
    private LocalDateTime updatedAt;

    /*
     * Auto set createdAt and updatedAt before first save.
     * @PrePersist runs automatically before INSERT.
     * We never set these manually — JPA handles it.
     */
    @PrePersist
    public void prePersist() {
        this.createdAt = LocalDateTime.now();
        this.updatedAt = LocalDateTime.now();
    }

    /*
     * Auto update updatedAt every time record is saved.
     * @PreUpdate runs before every UPDATE operation.
     * Tracks when doctor last edited the record.
     * Part of HIPAA audit trail PDF requires.
     */
    @PreUpdate
    public void preUpdate() {
        this.updatedAt = LocalDateTime.now();
    }
}