package com.medibook.provider.entity;

import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDate;
import com.fasterxml.jackson.annotation.JsonProperty;


/*
 * This is the Provider entity — it maps directly to the providers table in MySQL.
 *
 * Think of it like this:
 * User table stores basic info — name, email, password (for ALL users)
 * Provider table stores doctor specific info — specialization, clinic, rating
 *
 * Every doctor has TWO records:
 * 1. One in users table (basic account)
 * 2. One in providers table (professional profile)
 *
 * They are linked by userId field.
 * When patient searches for a doctor — we query providers table.
 * When doctor logs in — we query users table.
 */
@Entity
@Table(name = "providers")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Provider {

    /*
     * Unique ID for every provider profile.
     * Auto generated by MySQL — we never set this manually.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int providerId;

    /*
     * Links this provider profile to the users table.
     */
    @Column(nullable = false, unique = true)
    private int userId;

    /*
     * Type of medical specialization.
     */
    @Column(nullable = false)
    private String specialization;

    /*
     * Educational qualification of doctor.
     */
    @Column(nullable = false)
    private String qualification;

    /*
     * Number of years the doctor has been practicing.
     */
    private int experienceYears;

    /*
     * Short description about the doctor.
     */
    private String bio;

    /*
     * Name of clinic or hospital.
     */
    @Column(nullable = false)
    private String clinicName;

    /*
     * Full address of the clinic.
     */
    @Column(nullable = false)
    private String clinicAddress;

    /*
     * Average star rating given by patients.
     */
    private double avgRating = 0.0;

    /*
     * Is this doctor verified by admin?
     * Default is false when doctor first registers.
     * Admin reviews qualifications and sets this to true.
     * Doctor only appears in patient search when isVerified = true.
     */
 // To this:
    @Getter(AccessLevel.NONE)
    @Column(name = "is_verified", nullable = false, columnDefinition = "bit(1) default 0")
    private boolean verified = false;

    /*
     * Is this doctor currently available for appointments?
     */
    @Column(nullable = false)
    private boolean isAvailable = true;

    /*
     * When did this doctor join MediBook?
     */
    @Column(nullable = false, updatable = false)
    private LocalDate createdAt;

    /*
     * Auto set the createdAt date when provider is first saved.
     */
    @PrePersist
    public void prePersist() {
        this.createdAt = LocalDate.now();
    }

    /*
     * ================================
     * 🔥 FIX FOR VERIFICATION BUG
     * ================================
     *
     * Problem:
     * Lombok generates setter as setVerified()
     * but field name is isVerified → causes mismatch sometimes
     *
     * Solution:
     * We manually define setter so service layer works correctly
     *
     * This ensures:
     * → DB updates correctly
     * → Value persists after refresh
     * → Dashboard shows correct data
     */

   
 // NEW
    @JsonProperty("isVerified")
    public boolean isVerified() {
        return verified;
    }

    public void setVerified(boolean verified) {
        this.verified = verified;
    }
}